### ISSUE TITLE
Put mode is not idempotent

### ISSUE THREAD

**Issue by felipe1982** [mGageTechOps/ansible-role-module-credstash#2]
Thanks for the great role/module. It's handy to `put` credentials in storage.  Putting the value in the first time works well, but when run again, it fails. It is not idempotent.

OS: cygwin

Playbook
```yaml
- name: put a credstash credential
  hosts: localhost
  vars:
    credstash_version: '1.13.2'
    secrets:
      -
        mode: 'put'
        secret: 'mysecret'
        value: 'ApplesAreDelicious'
        region: 'ap-southeast-2'
  roles:
    - credstash
```
Error
```
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_70oKo8/ansible_module_credstash.py", line 51, in <module>
    main()
  File "/tmp/ansible_70oKo8/ansible_module_credstash.py", line 30, in main
    module.params.get('table'), module.params.get('context'))
  File "/usr/lib/python2.7/site-packages/credstash.py", line 293, in putSecret
    return secrets.put_item(Item=data, ConditionExpression=Attr('name').not_exists())
  File "/usr/lib/python2.7/site-packages/boto3/resources/factory.py", line 520, in do_action
    response = action(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(**params)
  File "/usr/lib/python2.7/site-packages/botocore/client.py", line 253, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/lib/python2.7/site-packages/botocore/client.py", line 543, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.ConditionalCheckFailedException: An error occurred (ConditionalCheckFailedException) when calling the PutItem operation: The conditional request failed

failed: [localhost] (item={u'region': u'ap-southeast-2', u'secret': u'mysecret', u'value': u'ApplesAreDelicious', u'mode': u'put'}) => {
    "failed": true,
    "item": {
        "mode": "put",
        "region": "ap-southeast-2",
        "secret": "mysecret",
        "value": "ApplesAreDelicious"
    },
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_70oKo8/ansible_module_credstash.py\", line 51, in <module>\n    main()\n  File \"/tmp/ansible_70oKo8/ansible_module_credstash.py\", line 30, in main\n    module.params.get('table'), module.params.get('context'))\n  File \"/usr/lib/python2.7/site-packages/credstash.py\", line 293, in putSecret\n    return secrets.put_item(Item=data, ConditionExpression=Attr('name').not_exists())\n  File \"/usr/lib/python2.7/site-packages/boto3/resources/factory.py\", line 520, in do_action\n    response = action(self, *args, **kwargs)\n  File \"/usr/lib/python2.7/site-packages/boto3/resources/action.py\", line 83, in __call__\n    response = getattr(parent.meta.client, operation_name)(**params)\n  File \"/usr/lib/python2.7/site-packages/botocore/client.py\", line 253, in _api_call\n    return self._make_api_call(operation_name, kwargs)\n  File \"/usr/lib/python2.7/site-packages/botocore/client.py\", line 543, in _make_api_call\n    raise error_class(parsed_response, operation_name)\nbotocore.errorfactory.ConditionalCheckFailedException: An error occurred (ConditionalCheckFailedException) when calling the PutItem operation: The conditional request failed\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE",
    "rc": 0
}
```

**Comment by simplyadrian** [comment]
Thank you for taking the time to show interest in improving our roles. While certainly possible to create secrets with the module our intended purpose was for fetching secrets. A put action would require a version flag after the first run. Our concern is exposing secrets in a play. Which is why we do secret creation as a one off step elsewhere i.e. Not in a play. This is not a scenario we have looked at but I will investigate.

**Comment by felipe1982** [comment]
Ansible `lookup` already *gets* from credstash. I love this module because it allows me to dynamically and automatically store credentials into credstash. Your module already does this very well and I commend you for it.

Would be nice for the module to do a simple check if `secrets.secret` already exists and then warn the user.

Thanks anyway for replying.

**Comment by felipe1982** [comment]
My secret in this case is creating a new Access Key and Secret with ansible `iam.py` module, and then storing that secret in credstash, so nothing gets _kept_ around on disk anywhere.  I'm rusty in Python, but I'll what I can put together. Cheers.

**Comment by felipe1982** [comment]
Oh, and I also changed `credstash_version` to `~` (null) so pip just gets whatever it thinks is _latest_ because hard coding a version is just icky 💩

**Comment by felipe1982** [comment]
You do have a point there.

**Comment by simplyadrian** [comment]
closed via https://github.com/mGageTechOps/ansible-role-module-credstash/pull/3
